service: StartIngestionJob
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1


functions:
  StartIngestionJob:
    handler: handler.lambda_handler
    events:
      - httpApi:
          path: /
          method: post
          
